### ISSUE TITLE
BleachBit v4.2.0 Deleting Firefox Bookmark Icons

### ISSUE THREAD

**Issue by TeslaMagic** [bleachbit/bleachbit#1081]
BleachBit v4.2.0 is deleting Firefox bookmark icons (favicons). This did not occur with v4.0.0.

Using Linux Mint Cinnamon v18.3, v19.3 and v20.0 and Firefox v84.0.1 (from repository).

This can be prevented by unchecking URL history under Firefox section in BleachBit or deleting the following from the firefox.xml file in the usr/share/bleachbit/cleaners directory:

<action command="mozilla.favicons" search="file" path="$$profile$$/favicons.sqlite"/>

**Comment by abitrolly** [comment]
Looks like a second appearance of https://github.com/bleachbit/bleachbit/issues/1017

I will try to test it on Fedora later today.

**Comment by az0** [comment]
Rados added a fix in 641b294be02f93fab228e14971069eb564a19597 .

@TeslaMagic 
Are you able to please test the fix by [running from source code](https://docs.bleachbit.org/dev/running-from-source-code.html)? It's fairly easy on most Linux systems.

The simple method is like this
```
sudo apt-get install git
git clone https://github.com/bleachbit/bleachbit.git
cd bleachbit
python3 bleachit.py
````

**Comment by az0** [comment]
I didn't get a response, but I will assume it is fixed. 

@TeslaMagic
If the same issue continues with the new version, please reopen this issue ticket.

**Comment by XhmikosR** [comment]
@az0 @rados this still happens with v4.4.0 (Firefox 89, Windows 10). But it doesn't happen for all the bookmark favicons.

**Comment by rados** [comment]
@XhmikosR 
Thanks for this notification. If you could paste the error message, it will help...

**Comment by XhmikosR** [comment]
There's no error message, but some of my bookmark favicons are going missing after running Bleachbit v4.4.0. Triple tested it on my VM.

**Comment by rados** [comment]
> There's no error message, but some of my bookmark favicons are going missing after running Bleachbit v4.4.0. Triple tested it on my VM.

Thank you very much. Would you be able to share one of those bookmarks? I mean the url...

**Comment by XhmikosR** [comment]
Sure thing. A couple are:

* `https://www.base64-image.de/`
* `https://lebab.unibtc.me/editor/`

**Comment by rados** [comment]
I saw the problem. Very interesting, some icons are kept differently in the icons database, I haven't noticed this before. I am working on covering those cases and then I will do more comprehensive tests. Thanks.

**Comment by az0** [comment]
Because it still happens, I retargeted this issue for 4.6.0.

**Comment by abitrolly** [comment]
Is there a Docker image we can use to test this?

**Comment by eleius** [comment]
I have the same issue using BleachBit 4.4.2 and Firefox 101.0 in Arch Linux. In BleachBit I have all flags checked for Firefox except for "passwords" and "vacuum".

I have hundreds of bookmarks, and about 10% of their favicons (always the same) are deleted after using BleachBit.

I also tried adding the following to the bleachbit.ini file, without success:

```
[whitelist/paths]
0_type = file
0_path = ~/.mozilla/firefox/qv5vjj2o.default-release/favicons.sqlite
1_type = file
1_path = ~/.mozilla/firefox/qv5vjj2o.default-release/favicons.sqlite-wal
```

**Comment by rados** [comment]
@eleius Thanks for this report. There is a fix in this direction that is not part of the official release yet. If you like you can give it a test run by running the app from source. Here you can see how to run from source the regular master branch:

https://docs.bleachbit.org/dev/running-from-source-code.html

When you are done with it you need to do a few more operations in order to checkout the pull request with the fix (#1333):

git fetch origin pull/1333/head:fix_favicon
git checkout fix_favicon

And with 'python3 bleachbit.py' you run the app with the fix. It would be interesting to know if this fixes your situation.

**Comment by eleius** [comment]
> It would be interesting to know if this fixes your situation.

I can confirm it fixes my issue, bookmark icons are not deleted anymore after cleaning. Thanks.
