### ISSUE TITLE
Linux Delete incomplete error

### ISSUE THREAD

**Issue by thejoker3000** [bleachbit/bleachbit#1097]
**Describe the bug**

The error happens everytime I try to delete the same folder:

Exception while running operation '_gui': ''utf-8' codec can't encode character '\udcf3' in position 146: surrogates not allowed'
Traceback (most recent call last):
  File "/usr/share/bleachbit/bleachbit/Worker.py", line 353, in run_operations
    for dummy in self.clean_operation(operation):
  File "/usr/share/bleachbit/bleachbit/Worker.py", line 160, in clean_operation
    for ret in self.execute(cmd, '%s.%s' % (operation, option_id)):
  File "/usr/share/bleachbit/bleachbit/Worker.py", line 132, in execute
    self.ui.append_text(line)
  File "/usr/share/bleachbit/bleachbit/GUI.py", line 630, in append_text
    self.textbuffer.insert(__iter, text)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 765, in insert
    Gtk.TextBuffer.insert(self, iter, text, length)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcf3' in position 146: surrogates not allowed

Disk space recovered: 13,5MB
Files deleted: 2
Errors: 1

**Expected behavior**
Expected it to delete permanently and no errors.

**Desktop (please complete the following information):**
 - OS: Latest of Kubuntu
 - BleachBit version latest

**Comment by az0** [comment]
Did you install BleachBit from the Ubuntu repository or from https://www.bleachbit.org/ ?

Please open BleachBit, click the hamburger menu (three horizontal lines), click Diagnostic, and report the version number there

**Comment by thejoker3000** [comment]
I believe I installed it from ubuntu repo.
Diagnostic isn't working for me. Not opening but **About** shows version 3.9.0

**Comment by thejoker3000** [comment]
![image](https://user-images.githubusercontent.com/53082621/105646864-87251780-5ea2-11eb-9277-c19f03cca528.png)

**Comment by thejoker3000** [comment]
Ok, I believe it has something to do with:
```
Clean file ?B /home/thejoker/.config/vlc/vlc-qt-interface.conf
Clean file ?B /home/thejoker/.config/vlc/vlc-qt-interface.conf
Clean file ?B /home/thejoker/.config/vlc/vlc-qt-interface.conf
```
If I go to the directory of **.config/vlc/** and manually remove vlc-qt-interface.conf, the error does not occur. Restarting VLC, closing it and retry, error appears again. So for some reason, it's detecting the file in the same folder more than once.

**Comment by thejoker3000** [comment]
Also, I just realized that I installed bleachbit from snap software "store".

**Comment by az0** [comment]
The VLC error was fixed in version 4.0.0 as mentioned here https://github.com/bleachbit/bleachbit/issues/740 

The UTF-8 error was fixed in 4.2.0 as mentioned here https://github.com/bleachbit/bleachbit/issues/874

Please [upgrade to BleachBit 4.2.0](https://www.bleachbit.org/news/bleachbit-420)

**Comment by az0** [comment]
Ubuntu has a "no rolling release" policy, so the version of BleachBit in the Ubuntu repository is typically old. Sometimes it's ancient.

**Comment by thejoker3000** [comment]
so I just removed bleachbit from my computer from snap store and installed the .deb package from the website.
Still get an error:

`Exception while running operation 'system': ''utf-8' codec can't encode character '\udcf1' in position 148: surrogates not allowed'
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 346, in run_operations
    for dummy in self.clean_operation(operation):
  File "/usr/share/bleachbit/Worker.py", line 160, in clean_operation
    for ret in self.execute(cmd, '%s.%s' % (operation, option_id)):
  File "/usr/share/bleachbit/Worker.py", line 132, in execute
    self.ui.append_text(line)
  File "/usr/share/bleachbit/GUI.py", line 607, in append_text
    self.textbuffer.insert(__iter, text)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 765, in insert
    Gtk.TextBuffer.insert(self, iter, text, length)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcf1' in position 148: surrogates not allowed`

**Comment by thejoker3000** [comment]
Ok, will close this now.
**Solution:**
- Remove bleachbit and config files from system
- Install the official package from bleachbit.org
- retry
- works
- good to go ;)

**Comment by az0** [comment]
This looks more like  https://github.com/bleachbit/bleachbit/issues/1709 fixed by ac6e8ec08e2f6b4fa6751f59e5b47ddc88083c80
