### ISSUE TITLE
google_chrome.sync cleanup no longer working

### ISSUE THREAD

**Issue by soundchekk** [bleachbit/bleachbit#397]
Chrome Version 69.0.3497.100 (Ubuntu 64bit)
Bleachbit - latest git-pull

The chrome sync cleaner won't clear the google sync login. 
I'm still logged in to the sync menu, even after running the chrome "google_chrome.*" cleaners.

This now also lets me relogin to e.g. gmail via that sync menu.

Let me know if you need more info.

**Comment by az0** [comment]
I downgraded to Chromium 65 on Ubuntu 18.04, and chromium.sync does not log out of the browser sync. 

There was a controversial change in Google Chrome 69 that automatically logs users into Google web sites when logged into the browser.

In any case, I started making changes to log out of the browser.

**Comment by soundchekk** [comment]
Chromium is not Chrome!

Your fix is not working on Chrome as it seems to me on the first glance.

Please reopen the issue.

**Comment by az0** [comment]
I fixed it for both. Here it is for Google Chrome: https://github.com/bleachbit/bleachbit/commit/4c155c707ef3791e208d347124c38eaca4a8bf05

**Comment by soundchekk** [comment]
It's still not working.

I'm still logged in into my google account after the cleaning.

I did see the sync error message in the upper right  corner now.

**Comment by soundchekk** [comment]
Just to mention it.

Make sure  - if possible - that only a "logout" from google_sync takes place.
Cleaning the google sync settings - basically setting them all to default "on" - should IMO be avoided.

**Comment by az0** [comment]
@jeroen7s Deleting "Local Storage" does not remove the authentication  on Google Chrome 71 (beta), and there is no IndexDB directory.

You mentioned a warning. I suggest testing on an alternative profile or making a backup. In this case, I used Google Chrome Beta which stores data in `~/.config/google-chrome-beta`

**Comment by Tobias-B-Besemer** [comment]
@soundchekk, can you give my cleaner a try?

It's PR #478, use v2.1.0 (latest)...

**Comment by soundchekk** [comment]
What do you want me to do exactly?

**Comment by az0** [comment]
@soundchekk 

You could copy his version of `google_chrome.xml` to replace the one that comes with BleachBit

**Comment by Tobias-B-Besemer** [comment]
@soundchekk, yes, then we see if it's already fixed, or start fixing it from the point I alread be...

**Comment by Tobias-B-Besemer** [comment]
@jeroen7s, you can give v2.2.0 a try, if you like! If you have a short look on the cleaner, you know what you have to do... ;-)

**Comment by Tobias-B-Besemer** [comment]
@jeroen7s, steps to go:
- First clean with the old google_chrome.xml & vivaldi.xml;
- Then test your modified google_chrome.xml!

Would be interesting to see if the new cleaner cleans already something more then the old one... ;-)

**Comment by Tobias-B-Besemer** [comment]
@soundchekk, I pushed v2.3.0 of the cleaner. In this version I remove a lot more Sync Data. I think this version should solve your problem... ;-) ...Give it a try! ;-)

@jeroen7s, I had a look on your suggestions in the Vivaldi-Cleaner... You suggested to clean $$profile$$/Local Storage/leveldb/ - we did that in the Chrome-Cleaner already in the DOM Storage Part... but I added the warning you suggested... and the cleaning of $$profile$$/Local Storage/leveldb/ again with your suggested cleaning of $$profile$$/IndexedDB/http* in the new Option "Local Storage"... ;-) ...So give it a try! ;-)

So, last word to all have @az0, so lets wait for his feedback and the changes he want... :-)

**Comment by Tobias-B-Besemer** [comment]
Btw.: If @az0 is OK with it, I will fork from this cleaner to a "universal code base", to fork from each Chromium-/Chrome-Based Browser we get info too... So BleachBit will support a lot of browsers in the future and the changes I made come to the Vivaldi-Cleaner, too and the cleaner maybe finally into the release, at any time... :-)

**Comment by jeroen7s** [comment]
@Tobias-B-Besemer is https://samy.pl/evercookie/ properly cleaned by the updated cleaner? or does it still recover the set "EverCookie" data after cleaning?

**Comment by Tobias-B-Besemer** [comment]
To be true: As my Google Chrome profile is one of my working profiles, I don't clean all out of my profile! I hoped you can tell me that... ;-)
