### ISSUE TITLE
GTK+ translations for buttons (gtk.mo) are missing in version 2.0 and 2.2

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#429]
Seems the strings 'Cancel' & 'Delete' from the buttons of the warning dialog before a cleanup, don't get translated. I searched for them in the German language file to have a look if I can patch them, but they are missing. Please have a look at the screenshot.

![2018-12-20 22_01_44-bleachbit](https://user-images.githubusercontent.com/11881073/50313663-63fe3180-04ac-11e9-83ca-28e2e4b19fac.jpg)

**Comment by az0** [comment]
They are missing from the BleachBit strings because they are stock GTK+. Specifically, they come from these lines in GuiBasic.py

````
    dialog.add_button(gtk.STOCK_CANCEL, gtk.RESPONSE_CANCEL)                    
    dialog.add_button(gtk.STOCK_DELETE, gtk.RESPONSE_ACCEPT) 
````

The stock strings should be translated, and later I will check more

**Comment by Tobias-B-Besemer** [comment]
'Close' seems also to be missing...

![2019-03-26 05_58_45-Einstellungen](https://user-images.githubusercontent.com/11881073/54972557-629d4300-4f8c-11e9-8a91-dc6fbb10500a.jpg)

**Comment by Tobias-B-Besemer** [comment]
All buttons... also "Copy"...

![2019-03-26 06_21_30-BleachBit](https://user-images.githubusercontent.com/11881073/54973284-8746ea00-4f8f-11e9-840a-dc12fcef2fcd.jpg)

**Comment by Tobias-B-Besemer** [comment]
![2019-03-26 06_22_53-BleachBit](https://user-images.githubusercontent.com/11881073/54973324-afcee400-4f8f-11e9-9cd6-74750b17008b.jpg)

**Comment by az0** [comment]
BleachBit version 1.8 had GTK+ translations stored in  `gtk.po` files like this

  >  23425  2015-06-19 21:03   BleachBit-Portable/share/locale/de/LC_MESSAGES/bleachbit.mo
   >  1024  2015-06-19 21:10   BleachBit-Portable/share/locale/de/LC_MESSAGES/gtk20.mo

The `gtk.mo` files are missing for all languages in version 2.0 and 2.2, so this is a bug.

Workaround: [download BleachBit 1.8 portable](https://www.bleachbit.org/download/old) and copy the `gtk20.mo` file from its `de` (German) directory to your directory (`share/locale/de`) next to the existing `bleachbit.mo` file

**Comment by Tobias-B-Besemer** [comment]
I don't need the translations of the buttons, but it should be fixed for other users...

**Comment by az0** [comment]
I see this is still an issue in the latest Git release with GTK 3

**Comment by mkhon** [comment]
I can not reproduce (buttons are translated properly for me, latest master ~3.9.0).

<img width="1148" alt="Screen Shot 2020-04-03 at 01 37 12 " src="https://user-images.githubusercontent.com/3022749/78289585-98d0b380-754c-11ea-9709-86c2ae342c5c.png">
<img width="1148" alt="Screen Shot 2020-04-03 at 01 38 15 " src="https://user-images.githubusercontent.com/3022749/78289589-9a01e080-754c-11ea-869d-9f7da83f126a.png">

**Comment by az0** [comment]
@mkhon 

Is this on your development system where you installed the GTK? 

I expect this is reproducible on a clean Windows system without GTK installed. I think the root cause is the translations are not copied into the BleachBit installer. Or, if they are, GTK doesn't know where to find them.
