### ISSUE TITLE
Some cleaner take long to "load" at start, when option "only needed" is checked ("Vuze Case")

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#512]
Some cleaner take long to "load" at start, when option "only needed" is checked ("Vuze Case")
My English... :-D

OK, I have now the "Vuze Case" also on BiglyBT and on my Windows Cleaner...

Is it really sure, that the check stops, after the first file, the cleaner finds ???

Can you display a bit more what the cleaner do in console for debugging ???

Whats about the case, I cleaned e.g. Vuze immediately before, then the cleaner can't find anything and have to run to the end, right?

Is maybe a < Detect >-Rule a solution for such scanners that have to scan a big amount of files ???

**Comment by az0** [comment]
About how many seconds does it take for Vuze and BiglyBT?

**Comment by Tobias-B-Besemer** [comment]
A lot! But my testing machine is very old...

**Comment by az0** [comment]
Able you able to help isolate exactly what is causing this? You mentioned it happens with Vuze, but when I look at `vuze.xml`, I do not see anything obvious that would cause this problem. To isolate the problem, would you please delete the `<option`> and `<action>` elements in `vuze.xml` until one action remains that makes it slow? Once the problem is isolated, it will be easier to solve.

**Comment by Tobias-B-Besemer** [comment]
OK. I set it on my to-dos-list... ^^

**Comment by Tobias-B-Besemer** [comment]
One try, one hit! ^^

I removed this line:
`<action command="delete" search="walk.files" path="$$Profile$$\" regex="\.[Bb][Aa][Kk]$"/>`

...and now it pass the check in normal time! ^^

**Comment by az0** [comment]
How many files are under `$$Profile$$`?

**Comment by Tobias-B-Besemer** [comment]
Many! ^^

**Comment by Tobias-B-Besemer** [comment]
Anyway: It takes up to some minutes till BB work again... :-/

**Comment by az0** [comment]
In your file browser, would you please right click on the root folder? Then bring up the properties, and it should give you a count.

This screenshot is what I mean
https://www.folder-size-explorer.com/images/folder-properties-size.png

**Comment by Tobias-B-Besemer** [comment]
^^ It was one of my hobbies in the past... ^^
![2019-04-19 22_11_45-Eigenschaften von Azureus](https://user-images.githubusercontent.com/11881073/56442285-78cec280-62f0-11e9-9210-f5ba7656d6d7.jpg)

**Comment by Tobias-B-Besemer** [comment]
I did know what you mean! ^^ I just needed some secs... ^^

**Comment by ppolewicz** [comment]
> One try, one hit! ^^
> 
> I removed this line:
> `<action command="delete" search="walk.files" path="$$Profile$$\" regex="\.[Bb][Aa][Kk]$"/>`
> 
> ...and now it pass the check in normal time! ^^

@Tobias-B-Besemer there is no such line in `vuze.xml`, never was. Where did you find it?

**Comment by az0** [comment]
@ppolewicz 
The line is from an open pull request

https://github.com/bleachbit/bleachbit/pull/462/files#diff-e3a08ce16efae5e4e6cbfcef163ffe87R73

**Comment by az0** [comment]
I just merged a change from Paweł Polewicz that could help this.

@Tobias-B-Besemer 
I have not heard from you from a while. Thanks for your patience with this one. Are you able to please quantify the improvement of BleachBit build 2.3.1128 from https://ci.bleachbit.org/ ?

**Comment by Tobias-B-Besemer** [comment]
@az0, sorry, was/be busy with other projects... Will try to test it those days...

**Comment by Tobias-B-Besemer** [comment]
I took now the time to test the case with v2.3.1139.
I see you followed my suggestion and display now more info what BleachBit is doing in the backgroud...
...unfortunately the "Vuze Case" still exist! I haven't measured and compaired time, but IMHO it still takes much to long! (Take maybe now up to 1 min. instead of up to 2 min. on my demo machine...)

![2019-07-17 02_33_45-Administrator_ C__Windows_system32_cmd exe - bleachbit_console exe  --gui --debu](https://user-images.githubusercontent.com/11881073/61339294-76233100-a83d-11e9-9adb-b5fc74a0c10e.jpg)

**Comment by ppolewicz** [comment]
@Tobias-B-Besemer what is inside that directory? Just a large number of files or a lot of shallow directories, or a lot of deep directories? If we knew what it is, that would really shorten the testing cycle.

**Comment by az0** [comment]
@Tobias-B-Besemer  Would you mind running this command inside the directory  to capture the filenames and directory structure? 

Command: `dir /b > listing.txt`

GitHub accepts .txt files as attachments, or you could email me privately

**Comment by Tobias-B-Besemer** [comment]
I guess this is the most interesting data...

![2019-07-17 17_25_03-Administrator_ C__Windows_system32_cmd exe](https://user-images.githubusercontent.com/11881073/61388683-47966c00-a8b8-11e9-83a0-66aef4be3c23.jpg)
![2019-07-17 17_25_27-Administrator_ C__Windows_system32_cmd exe](https://user-images.githubusercontent.com/11881073/61388776-4d8c4d00-a8b8-11e9-95d1-d94382380e9f.jpg)
![2019-07-17 17_25_38-Administrator_ C__Windows_system32_cmd exe](https://user-images.githubusercontent.com/11881073/61388870-51b86a80-a8b8-11e9-8b3c-7b6bee13fb7d.jpg)
![2019-07-17 17_17_28-C__Users_Administrator_AppData_Roaming_Azureus_active](https://user-images.githubusercontent.com/11881073/61388947-5e3cc300-a8b8-11e9-9632-691825f759b6.jpg)
![2019-07-17 17_21_01-C__Users_Administrator_AppData_Roaming_Azureus_torrents](https://user-images.githubusercontent.com/11881073/61388973-698fee80-a8b8-11e9-8d48-65de6906d35c.jpg)

...so basically some folders with a lot of small files...

**Comment by Tobias-B-Besemer** [comment]
...but my improved Windows Cleaner have now issues, too. And there I'm scaning the Windows folder...

I guess it just take to long to scan for all varians... E.g.: regex="\.[Bb][Aa][Kk]$ ...but a variant like *.bak that is not case sensitive doesn't exist, right?

**Comment by ppolewicz** [comment]
we could add it, the question is whether it could be faster than your current case.

@Tobias-B-Besemer could you please measure the performance of:
1. the version you used when reporting the ticket
2. v2.3.1128 or newer (with cache patch)
? You can just use a stopwatch if you want to, but please make sure you drop kernel cache between the tests (on Windows I think it may be easiest to just reboot before performing each test) (I am mentioning this because tests ran on linux run in like 1/3rd of the time if the kernel cache is not dropped before the test).

Also one more thing, during the execution of the problematic code, please use task manager and find out whether it's your CPU that is being maxed out (100% on a single-core machine, 25% on quad-core etc usually indicate this) or is it the hard drive that is loaded to 100%, or both?

Also please confirm, are you using a hdd?

**Comment by ppolewicz** [comment]
I ran a test on `/usr` with 274442 files, that took 5s, ran another one on a flat directory with 200k files which took 15s (but `find` takes 11s).

Is your hard drive fragmented or something?

**Comment by ppolewicz** [comment]
Oops, I ran that test on the wrong VM, it was on SSD.

Now I ran it on the right thing, 20k files in a flat directory take 0m51,780s, but 97% of that time is spent on python waiting for the hard drive.

On `/usr` it took 42s, 86% of that waiting, 1.4% on filter_path (where regex is).

It's `os.walk` that is consuming practically all the time, not the regex engine. Parallelizing regex with directory scanning won't help much (we'd get like 2%, but only if the GIL war won't make it even worse).

**Comment by az0** [comment]
On my Linux machine with a NVME, the scanning with a regex is fast. I haven't tried it on Windows with a HDD. Maybe Python functions make excessive OS calls on Windows in os.walk().

**Comment by ppolewicz** [comment]
We are hitting the old implementation of `os.walk` in python 2.7, please see here: https://www.python.org/dev/peps/pep-0471/#os-walk

The "right" solution is to upgrade python to a supported version. 2.7 EOL is imminent, so it has to be done very soon anyway. A "wrong" solution would be to add a dependency on [scandir](https://pypi.org/project/scandir/) external package and then we'd also need to reimplement `glob.glob()` (which won't be upgraded by external scandir package because glob will keep using the slow `os.walk()` from 2.7). In essence we would be backporting a portion of 3.5 into 2.7, only to delete it a couple of months later when 2.7 is EOL. Therefore the real solution seems to be to upgrade python version and that will boost the performance significantly.

A good demo of this:
```python
from bleachbit import FileUtilities

print(
    sum(
        1
        for _ in FileUtilities.children_in_directory('/media/sf_share/foo3/')
    )
)
```

first, on 2.7:
```bash
$ time python test.py 
20000

real	0m51,411s
user	0m0,374s
sys	0m1,081s
```
and then after a few minutes of hacking to get it to work on python3:
```bash
$ time python3 test.py 
20000

real	0m0,364s
user	0m0,120s
sys	0m0,057s
```
so **141 times faster** on my machine.

One more test on python3 version, on a larger data set:
```bash
$ time python3 test.py 
200000

real	0m1,013s
user	0m0,766s
sys	0m0,081s
```

Bleachbit uses `os.walk` in many places, I'd expect a good improvement of performance overall.

**Comment by az0** [comment]
Pawel implemented an alternative scanning function that is objectively better measured multiple ways. I expect it will be noticable improvement for deep scan and similar operations that scan many files but match few files. For example, out of the thousands of files under the Vuze directory, there may be only a few files that are deleted.

Please try Windows build 2.3.1187

**Comment by Tobias-B-Besemer** [comment]
Hi!

Sorry for being late! But I'm a freelancer and I have ATM to work really hard and don't have much spare time, but I must pay my bills...

<br>

> Is your hard drive fragmented or something?

No! But my test machine is really old, expecting the harddrives...

<br>

> ...20k files in a flat directory take 0m51,780s, but 97% of that time is spent on python waiting for the hard drive.

My tests took around 3 min. if not cached, but the only thing I can imagen what is high, is the I/O, BB doesn't read much data from the HD...
If cached it just took seconds...
Just one question: Does regex read file per file, or the complete directory and then analyse it ???
I can imagen that reading the complete directory is faster then making one file access after each other.

What new is, is that BB "hangs without reaction", says the recources monitor...

Did my tests with BleachBit-2.3.1139-setup.exe, but will make a new run with a new setup...

**Comment by Tobias-B-Besemer** [comment]
Now it's faster!

But BB read a lof of files...
![2019-08-04 21_45_32-Ressourcenmonitor](https://user-images.githubusercontent.com/11881073/62428407-e0731700-b701-11e9-994b-c2e8a8a0d45e.png)
![2019-08-04 21_46_43-Ressourcenmonitor](https://user-images.githubusercontent.com/11881073/62428408-e49f3480-b701-11e9-90a4-464064f8f91b.png)

...and this are screenshots from my last test...
![2019-07-19 08_44_50-Ressourcenmonitor](https://user-images.githubusercontent.com/11881073/62428410-eec13300-b701-11e9-9d23-77f1e95e52f6.jpg)
![2019-07-19 08_50_46-Ressourcenmonitor](https://user-images.githubusercontent.com/11881073/62428411-f08af680-b701-11e9-8e1d-0c4d4ae2c461.jpg)

**Comment by Tobias-B-Besemer** [comment]
And I see the old version already used 64 not 32...

**Comment by Tobias-B-Besemer** [comment]
> What new is, is that BB "hangs without reaction", says the recources monitor...

@az0, do you have recognized this comment ???

Here is a SS where it starts to hang:
![2019-09-10 23_16_23-Administrator_ C__Windows_system32_cmd exe - bleachbit_console exe  --gui --debu](https://user-images.githubusercontent.com/11881073/64651658-4d28b200-d422-11e9-8375-f5913bb690bf.jpg)
