### ISSUE TITLE
ValueError: Not a boolean: ['False'] on BleachBit 2.2 and Windows 7

### ISSUE THREAD

**Issue by polandkraish** [bleachbit/bleachbit#562]
In all above tested versions bleachbit gives me the exact same log files:

Traceback (most recent call last):
  File "bleachbit\Options.pyo", line 192, in get_tree
  File "ConfigParser.pyo", line 370, in getboolean
ValueError: Not a boolean: ['True']
Traceback (most recent call last):
  File "bleachbit.py", line 45, in <module>
  File "bleachbit\GUI.pyo", line 920, in __init__
  File "bleachbit\GUI.pyo", line 850, in create_window
  File "bleachbit\GUI.pyo", line 487, in create_operations_box
  File "bleachbit\GUI.pyo", line 71, in __init__
  File "bleachbit\GUI.pyo", line 101, in refresh_rows
  File "bleachbit\Options.pyo", line 130, in get
  File "ConfigParser.pyo", line 370, in getboolean
ValueError: Not a boolean: ['False']

Using Win 7. Installed and reinstalled multiple times. Downloaded from the official website and Sourceforge. I have not python installed. Bleachbit portable is fine.

**Comment by az0** [comment]
1. Can you think of any application that would have modified BleachBit's configuration in the file `%AppData%\BleachBit\BleachBit.ini`?
2. Go to the folder `%AppData%\BleachBit` and rename `BleachBit.ini` to another name. Then start BleachBit. It should work. If you need more detailed instructions, let me know.
 
If step 2 works, please send me the bad .ini file. To attach it here, zip it first. Alternatively, you could email it to me directly

**Comment by az0** [comment]
3. Did you use the Chocolately package v2.2.0.20190520?

**Comment by az0** [comment]
I am closing for lack of response, and I will assume this is like issue #560, which is fixed. If renaming the .ini file does not work, reopen the issue.  If you are not using Chocolately, please add a comment.

**Comment by polandkraish** [comment]
Sorry for the delay. The tweak does work, however, other programs like gtkhash are affected. I am unable to use them. Winapp.2 also does not work with this tweak.

**Comment by polandkraish** [comment]
The GtK problem seems to be a problem from my AVG software. However even disabling it I still cannot use Winapp.2 and every time I need to change the bleachbit.ini after every cleanup.

**Comment by az0** [comment]
Interesting, recently there were reports that AVG and Avast were corrupting the Firefox configuration

https://www.ghacks.net/2019/06/14/if-you-lost-all-passwords-in-firefox-read-this/

I know the password protection feature seems different, but I am wondering if you have this problem after updating to virus definition 19061402
https://support.mozilla.org/en-US/kb/passwords-disappearing-avg-security-software

**Comment by az0** [comment]
I have not been able to reproduce this or fix the root cause, but I added a workaround to automatically detect and delete corrupt configuration. You can test it in recent builds.

https://ci.bleachbit.org/

**Comment by az0** [comment]
Would you mind sending me a copy of your corrupt configuration? You can attach it here on GitHub (if you zip it or rename to .txt) or send it to me by [email](https://www.bleachbit.org/press).

**Comment by az0** [comment]
@polandkraish Are you using BleachBit in English, or is BleachBit translated?

**Comment by az0** [comment]
I still can't reproduce the problem. I need more information, and I haven't heard back about some questions. Please reopen this issue if you still have the problem and can answer some more questions.

**Comment by az0** [comment]
I haven't been able to reproduce the corruption, but you could test the workaround for the symptoms in  the newly-released [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta)

**Comment by az0** [comment]
For cross reference, the same `ValueError` as here was reported  with BleachBit 3.9 https://bugs.launchpad.net/ubuntu/+source/bleachbit/+bug/1933289
