### ISSUE TITLE
Application window stays minimized with dual monitors, Windows 10, BleachBit 3

### ISSUE THREAD

**Issue by notonymous** [bleachbit/bleachbit#663]
On Win10, BB 3.0 will sometimes stay minimised in the task bar and cannot be restored to a normal window. 
(a) Sometimes this happens if I close BB when the window is open on one monitor and then open BB later in a different multi-monitor configuration. 
(b) Sometimes this happens when I maximise the BB window on a monitor that is not the primary monitor and then minimise the window; I can't restore the window and have to kill the process.

I have reverted to BB 2.2

`Microsoft Windows 10 Enterprise Version 10.0.17134 Build 17134`

**Comment by az0** [comment]
Do the monitor happen changes while BleachBit is running or terminated?

There were two related changes between 2.2 and 3.0. One was changing the old GTK version 2 to GTK 3. The other was remembering the window position, size, and state: this happens only when BleachBit starts.

**Comment by notonymous** [comment]
in (a), monitors change while BB is terminated.
in (b), monitors change while BB is running.

**Comment by az0** [comment]
@notonymous 
Would you please test build [3.0.1.1348](https://ci.appveyor.com/project/az0/bleachbit/builds/28581706/artifacts)? The portable version is fine, if you don't want to affect your main installation.

This special build will check the geometry of the current screen before trying to restore the saved window positio . Restoring the window size, position, and state (full screen/unmaximized) was a new feature in BleachBit 3.0.

**Comment by LifeIsADeflatingVest** [comment]
Just adding that I have a very similar issue, both on Windows 7 and Windows 10, both with the portable and the .exe versions:  BB 3.0. I can see the process in task manager, but there is no window (not even minimized). I also tried the test build above, and the issue persists.

**Comment by notonymous** [comment]
> 
> @notonymous
> Would you please test build [3.0.1.1348](https://ci.appveyor.com/project/az0/bleachbit/builds/28581706/artifacts)? The portable version is fine, if you don't want to affect your main installation.
> 

The test build didn't fix the problem on my machine. In particular, the first test I tried (b):
* opened BB on my main (large monitor)
* moved BB to a secondary (laptop) monitor
* maximised BB window on the secondary monitor
* minimised BB to task bar

At that point, BB sits in the task bar but I can't restore the window.

**Comment by az0** [comment]
@notonymous 
Good description. Yes, I can reproduce that on Windows 10 with BleachBit 3 and two monitors. In my case, it was stuck since it was maximized on the second monitor, and I could see in the log that it thought it was maximized.

**Comment by LifeIsADeflatingVest** [comment]
Well, I only have one monitor, and I have the issue both on the desktop and the laptop.

**Comment by az0** [comment]
I opened a contract to fix this bug, so I hope soon we'll have a new solution to test.

**Comment by az0** [comment]
For reference, here is a similar issue with a single screen:
https://www.bleachbit.org/forum/problem-accessing-viewing-new-30-update-windows-10

**Comment by mkhon** [comment]
this appears to be a bug in gtk3 on Windows: when maximize() is called (whether when window size/position is restored during startup or when user clicks "Maximize") and the window is currently at the secondary monitor gtk3 moves the window off the screen:

```
on_window_state_event: <flags GDK_WINDOW_STATE_MAXIMIZED | GDK_WINDOW_STATE_FOCUSED of type Gdk.WindowState>
on_configure_event: (x, y) = (root_x=1844, root_y=0), (w, h) = (width=819, height=574), screen (w, h) = (1741, 691)
```

**Comment by az0** [comment]
@LifeIsADeflatingVest 
@notonymous 
Would you please test Max's fix?  I haven't merged it in yet, so it's currently available only here: build [3.0.1.1387](https://ci.appveyor.com/project/az0/bleachbit/builds/28901991/artifacts)

**Comment by LifeIsADeflatingVest** [comment]
Sadly, the problem persists (tested the portable version on Windows 10). It runs, appears on task manager (taking some 30% of CPU) but there is no window visible, minimized or not.

**Comment by az0** [comment]
@LifeIsADeflatingVest  Thank you for testing. I am still hoping we can find a good fix.

In the forum,  draconianlord  reported an improvement with the new build.

**Comment by mkhon** [comment]
Bleachbit not showing even as minimized is a different issue (not a "maximize" issue).

@LifeIsADeflatingVest can you run bleachbit_console.exe (may be with --debug) and attach the log here?

**Comment by notonymous** [comment]
> 
> 
> @LifeIsADeflatingVest
> @notonymous
> Would you please test Max's fix? I haven't merged it in yet, so it's currently available only here: build [3.0.1.1387](https://ci.appveyor.com/project/az0/bleachbit/builds/28901991/artifacts)

Sorry, still doesn't fix the issue.

**Comment by mkhon** [comment]
@notonymous can you run bleachbit_console.exe --debug --gui and provide the console output?

**Comment by notonymous** [comment]
> 
> 
> @notonymous can you run bleachbit_console.exe --debug --gui and provide the console output?

~~~
BleachBit version 2.2
Git revision 4e1f2717
GTK+ version 2.24.10
SQLite version 3.26.0
FSE = mbcs
local_cleaners_dir = None
locale_dir = C:\Program Files (x86)\BleachBit\share\locale\
options_dir = C:\Users\theUser\AppData\Roaming\BleachBit
personal_cleaners_dir = C:\Users\theUser\AppData\Roaming\BleachBit\cleaners
system_cleaners_dir = C:\Program Files (x86)\BleachBit\share\cleaners\
locale.getdefaultlocale = ('en_CA', 'cp1252')
os.path.expanduser('~') = C:\Users\theUser\
platform.win32_ver[1]() = 10.0.17134
platform.platform = Windows-10-10.0.17134
platform.version = 10.0.17134
sys.argv = ['C:\\Program Files (x86)\\BleachBit\\bleachbit_console.exe', '--debug', '--gui']
sys.executable = C:\Program Files (x86)\BleachBit\bleachbit_console.exe
sys.version = 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = False
__file__ = C:\Program Files (x86)\BleachBit\library.zip\bleachbit\Diagnostic.pyo
~~~

**Comment by notonymous** [comment]
> 
> 
> @notonymous can you run bleachbit_console.exe --debug --gui and provide the console output?

~~~
BleachBit version 3.0.1
Build number 1387
GTK version 3.18.9
SQLite version 3.28.0
FSE = mbcs
local_cleaners_dir = \bb3\BleachBit-Portable\cleaners
locale_dir = \bb3\BleachBit-Portable\share\locale\
options_dir = \bb3\BleachBit-Portable
personal_cleaners_dir = \bb3\BleachBit-Portable\cleaners
system_cleaners_dir = \bb3\BleachBit-Portable\share\cleaners\
locale.getdefaultlocale = ('en', 'cp1252')
os.path.expanduser('~') = C:\Users\theUser\
platform.win32_ver[1]() = 10.0.17134
platform.platform = Windows-10-10.0.17134
platform.version = 10.0.17134
sys.argv = ['bleachbit_console.exe', '--debug-log=bb.log', '--gui']
sys.executable = \bb3\BleachBit-Portable\bleachbit_console.exe
sys.version = 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 20:49:36) [MSC v.1500 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = False
__file__ = \bb3\BleachBit-Portable\library.zip\bleachbit\Diagnostic.pyo
~~~

**Comment by Tobias-B-Besemer** [comment]
@az0, why you close this issue, when both user reporting in this issue, still have problems? Sure, first fix is landed, but to be true, if I would be one of the two reporter, I would now feel a bit stupid... ;) ...just wanna saying that... Sorry!

**Comment by Tobias-B-Besemer** [comment]
No clue if it have to do with it any, but I found to pages that maybe can have to do with it...
https://gitlab.gnome.org/GNOME/gtk/issues/1477
https://developer.gnome.org/gtk3/stable/ch32s10.html

**Comment by az0** [comment]
> @az0, why you close this issue, when both user reporting in this issue, still have problems? Sure, first fix is landed, but to be true, if I would be one of the two reporter, I would now feel a bit stupid... ;) ...just wanna saying that... Sorry!

In issue #712, LifeIsADeflatingVest stated that he can no longer reproduce the issue.

I am re-opening the issue because the problem still exists for notonymous.

**Comment by TheHundredthIdiot** [comment]
This may be of help.... have today the exact issue detailed here and originally on the forum with 3.0 so nstalled 3...1387 over both 3.0 and 2.2 but neither route resolved the problem (2.2 ran consistently well).

Subsequenlty reverted to 2.2 and installed 3...1348 over 2.2 and problem fixed - then installed 3.0 over 3...1348 and resolved there too...

**Comment by Medi223** [comment]
W10 1909, BB 3.0, dual monitors - Not sure if its the same issue, but when I start BB it is completely invisible/not there, I reinstalled and it happens every time I run it, however, I solved the issue via Task Manager. https://imgur.com/a/tT1a6to

**Comment by az0** [comment]
> This may be of help.... have today the exact issue detailed here and originally on the forum with 3.0 so installed 3...1387 over both 3.0 and 2.2 but neither route resolved the problem (2.2 ran consistently well).
> 
> Subsequenlty reverted to 2.2 and installed 3...1348 over 2.2 and problem fixed - then installed 3.0 over 3...1348 and resolved there too...

@TheHundredthIdiot 
Thank you for the comment, but this is confusing because I don't see any changes (between 3.0 and build 1348) that would fix the problem. Build 1348 added more verbose logging. There was an earlier change to add four-part build numbers, but otherwise there were no code changes.

**Comment by az0** [comment]
> W10 1909, BB 3.0, dual monitors - Not sure if its the same issue, but when I start BB it is completely invisible/not there, I reinstalled and it happens every time I run it, however, I seemed to have solved the issue via Task Manager. https://imgur.com/a/tT1a6to

@Medi223 
Thanks for your help trying to solve this mystery. Please tell me more about how you used Task Manager. (I didn't understand from the screenshot.)

**Comment by Medi223** [comment]
> @Medi223
> Thanks for your help trying to solve this mystery. Please tell me more about how you used Task Manager. (I didn't understand from the screenshot.)
Task Manager can minimize and maximise windows, meaning even when the window is invisible/off-screen TM can maximise it back, which is what I did. I couldn't replicate it with BB, but it shows up for VLC - https://imgur.com/aZGwVPz

**Comment by Trasgato** [comment]
I had the same problem which BB, Windows 10 and 2 monitor’s (1920 x 1080).  After open  BleachBit (portable or installer version) in my second monitor and maximizing it, it’s disapear. 

I have solved it modifiying the “bleachbit.ini” file, located in:
C:\Users\<USER>\AppData\Roaming\bleachbit.ini

changing the next parameters values for 1:
window_x = 1
window_y = 1

Hope that helps

**Comment by az0** [comment]
The other day I released [BleachBit 3.1 beta](https://www.bleachbit.org/news/bleachbit-31-beta) which will become 3.2 final. It doesn't have any significant changes since the build I mentioned weeks ago in this thread.

There is also a preview of BleachBit 4.0 built on Python 3 instead of Python 2. This is not a small change, so maybe it's better. **Would someone please test it as [build 1507](https://ci.bleachbit.org/?prefix=dl/3.1.0.1507/)?**

The version number 3.1 here is misleading because it's not like the 3.1 beta, and I'll fix that for future builds.

**Comment by notonymous** [comment]
> 
> There is also a preview of BleachBit 4.0 built on Python 3 instead of Python 2. This is not a small change, so maybe it's better. **Would someone please test it as [build 1507](https://ci.bleachbit.org/?prefix=dl/3.1.0.1507/)?**
> 
> The version number 3.1 here is misleading because it's not like the 3.1 beta, and I'll fix that for future builds.

Sorry for the delay in responding. Unfortunately, I don't see any difference with the 4.0 build -- the same problems persist.

**Comment by Trasgato** [comment]
Problem solved in all Beta version for this OS:
Windows 10 pro 64bits
platform.win32_ver[1]() = 10.0.18362
platform.platform = Windows-10-10.0.18362
platform.version = 10.0.18362

A little observation: 
If the last version has been installed “for me” and the Beta version is installed for “all users” both version will be installed in the system at the same time.  In this case is possible to have an error (last version) and problem solved (beta version) at the same time too.

Curiosity (2 versions install):
1- open last version in second monitor and maximize: error
2- don’t close last version and open beta version: error
3- close BB
4- open beta: solved

If close Beta (maximize) in second monitor, next open last version: error.
If move Beta to the first monitor and close:  no problem if open last version.

Nice work that version change! it’s not easy.

**Comment by notonymous** [comment]
> 
> 
> Problem solved in all Beta version for this OS:
> Windows 10 pro 64bits
> platform.win32_ver1 = 10.0.18362
> platform.platform = Windows-10-10.0.18362
> platform.version = 10.0.18362
> 
Not solved for me in beta. I am using the portable versions so some of your observations are not applicable to me.

**Comment by Trasgato** [comment]
> Not solved for me in beta. I am using the portable versions so some of your observations are not applicable to me.

It’s curious, I just tried in a  windows 7 (dual core) computer:
platform.win32_ver[1]() = 6.1.7601
platform.platform = Windows-7-6.1.7601-SP1
platform.version = 6.1.7601

with same result.

Monitor configuration:
text size: 100%
Resolution: 1920x1080, 1920x1080
Orientation: landscape
Multiple displays: Extend 
Both monitor in the same graph

I have tried with different resolutions, text size and displays position’s, same result: no problem detect.

**Comment by notonymous** [comment]
Using BleachBit-3.1.0.1484-portable, I find I can affect the behaviour by modifying "window_x" in the BleachBit.ini file:
- if the window disappears when maximising on my secondary monitor, window_x is set to a negative value (-1366) where 1366 is the horizontal resolution of my secondary monitor.
- if I maximise BB on my primary monitor, window_x is set to a positive number.
- if I do not maximise BB, then I can drag it around to different monitors with no problem, but the value of window_x is always a positive number.

So maybe the setting of window_x to a negative number is symptomatic of the problem??

**Comment by Trasgato** [comment]
Yep.  Little error detect.  If the firs monitor  resolution is lower than the second monitor the window_x position take incorrect values.  After BB maximize in second monitor and close it:

Monitor 1 resolution higher than monitor 2 resolution:
monitor 1: 1920x1080 // monitor 2: 1920 x 1080 => window_x = 1920
monitor 1: 1920x1080 // monitor 2: 1600 x 1024 => window_x = 1920
monitor 1: 1920x1080 // monitor 2: 1366 x 768 => window_x = 1920

Monitor 1 resolution lower than monitor 2 resolution:
monitor 1: 1600 x 1024 // monitor 2: 1920 x 1080 => window_x = 3200
monitor 1: 1366 x 768  // monitor 2: 1920 x 1080 => window_x = 2732
monitor 1: 1280x1024 // monitor 2: 1920 x 1080 => window_x = 2560
monitor 1: 1280x1024 // monitor 2: 1366 x 768 => window_x = 2560

In all cases:
window_y = 0
window_width = monitor 2 width
window_height = monitor 2 height

> So maybe the setting of window_x to a negative number is symptomatic of the problem??

Yes, “ window_x value” is to blame for the headache, maybe your first monitor resolution is lower than the second?

**Comment by notonymous** [comment]
> 
> > So maybe the setting of window_x to a negative number is symptomatic of the problem??
> 
> Yes, “ window_x value” is to blame for the headache, maybe your first monitor resolution is lower than the second?
>
I have the same problem regardless of whether the monitor resolutions are the same or different.

**Comment by Trasgato** [comment]
> I have the same problem regardless of whether the monitor resolutions are the same or different.

Catch! (I think…)

If the second monitor is on the LEFT of the first, “window_x” take a negative value and don’t show nothing.
window_x = -1920
window_y = 0
window_width = 1920
window_height = 1080

If the second monitor is under the first all correct:
window_x = 0
window_y = 1080
window_width = 1920
window_height = 1080

If the second monitor is over the first, the negative value appears in “window_y” and don’t show:
window_x = 0
window_y = -1080
window_width = 1920
window_height = 1080

Another question:
For this configuration:
window_x = 0
window_y = 0
window_width = 800
window_height = 600

If the position of the second monitor on the first is:
top left → BB show in the second monitor (at the top left)
top right → don’t show
bottom left → don’t show
bottom right →  BB show in the first monitor (at the top left)

I think that windows take the “monitor space” from the upper left corner to the monitor in the upper left position regardless of the monitor number.

**Comment by mkhon** [comment]
Additional fix: #835

**Comment by az0** [comment]
To the several people who have experienced this problem, **would you please test Max's new fix today**? In a few minutes, there will be a 3.9.1.x build available on the [CI site](https://ci.bleachbit.org/). Please test and let us know whether it helped.

**Comment by notonymous** [comment]
> To the several people who have experienced this problem, would you please test Max's new fix today? In a few minutes, there will be a 3.9.1.x build available on the CI site. Please test and let us know whether it helped.

I tested BleachBit-3.9.1.1589-portable and the problem seems to be fixed -- I could move the BB window between monitors, maximise and minimise on any monitor, without losing the window. 

Based on my limited testing, I am in favour of closing this issue.

**Comment by Trasgato** [comment]
Hi, after test “BleachBit-3.9.1.1589-portable” version in different monitor position (2 monitors) and resolutions if maximize and don’t change monitors positions, all correct.

The problem arise if maximize, close, change monitor 2 position, open and if BB and maximize, for example:
- open BB (any position)
- move BB to monitor 2 (position 2.2)
- maximize in 2.2 position
- close
- change monitor position 2.2 for 2.3
- open (BB will appear on monitor 1 maximize)
- maximize (despite being maximized)

BB disappears and the error persist, for recover is necessary change the second monitor position, close and open.

Generally if BB is maximized on second monitor and change monitor position 2, when BB appears on monitor 1 (not on monitor 2) if it is maximized, despite being maximized, the error persist.  Very rare error.

![monitorPosition](https://user-images.githubusercontent.com/36175253/78229893-e0b1f500-74d0-11ea-998d-293bdbf58543.jpg)

**Comment by mkhon** [comment]
@Trasgato this is yet another corner case (restoring a window position outside of available monitors).

I believe I fixed everything in #836

**Comment by notonymous** [comment]
> 
> 
> @Trasgato this is yet another corner case (restoring a window position outside of available monitors).

As a quick workaround, could you add a preference to NOT remember the window position when closed?

**Comment by mkhon** [comment]
Maximize on Linux fixed in #837

**Comment by az0** [comment]
> > To the several people who have experienced this problem, **would you please test Max's new fix today**? In a few minutes, there will be a 3.9.1.x build available on the [CI site](https://ci.bleachbit.org/). Please test and let us know whether it helped.
> 
> Hi, after test “BleachBit-3.9.1.1589-portable” version in different monitor position (2 monitors) and resolutions if maximize and don’t change monitors positions, all correct.
> 
> The problem arise if maximize, close, change monitor 2 position, open and if BB and maximize, for example:

@Trasgato 
Thank you for testing, and great feedback. Would you please re-test a recent build mark 3.9.1 from [the CI site](https://ci.bleachbit.org/)? There are more fixes now.

**Comment by sjudenim** [comment]
Tested all of the 3.9x releases. Still no luck with #821

**Comment by az0** [comment]
Notonymous originally opened this issue, and he recently wrote he's in favor of closing it, so let's do that. We made progress, and it works for him,

> Tested all of the 3.9x releases. Still no luck with #821

@sjudenim 
You have your [own issue](https://github.com/bleachbit/bleachbit/issues/821), so let's continue the conversation there
